# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_beachstorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachstorypage',
            name='beach_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='explorer.Beaches', to_field=b'BeachID'),
            preserve_default=False,
        ),
    ]
