# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0016_auto_20160801_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachstorypage',
            name='beach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='explorer.Beaches'),
        ),
    ]
