# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0018_auto_20160802_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachstorypage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='explorer.CustomImage'),
        ),
    ]
