# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-21 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0019_auto_20160802_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDataHistoryAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('PrecipitationIn', models.CharField(blank=True, max_length=10, null=True)),
                ('BeachID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Beaches')),
            ],
        ),
    ]
