# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-06-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0020_weatherdatahistoryapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.DateField()),
                ('NumberOfSamples', models.IntegerField()),
                ('TotalPassSamples', models.IntegerField()),
                ('TotalDryWeatherSamples', models.IntegerField()),
                ('DryWeatherPassSamples', models.IntegerField()),
                ('TotalWetWeatherSamples', models.IntegerField()),
                ('WetWeatherPassSamples', models.IntegerField()),
                ('MaxValueWet', models.IntegerField()),
                ('MaxValueDry', models.IntegerField()),
                ('BeachID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Beaches')),
            ],
        ),
    ]
