# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-06-28 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0021_annualscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyWeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeUTC', models.DateTimeField()),
                ('PrecipitationIn', models.CharField(blank=True, max_length=10, null=True)),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.WeatherStations')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyWeatherDataPWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeUTC', models.DateTimeField()),
                ('PrecipitationIn', models.CharField(blank=True, max_length=10, null=True)),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.WeatherStations')),
            ],
        ),
    ]
