# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-26 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0023_auto_20190628_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAvgPrecip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('AvgPrecipitationIn', models.FloatField()),
            ],
        ),
    ]
