# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-26 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0024_dailyavgprecip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyAvgPrecip',
            new_name='AnnualAvgPrecip',
        ),
    ]
